'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowRight,BookOpen,Search,Settings2,Sparkles,X,ExternalLink,ChevronDown,ArrowLeft,LoaderCircle} from 'lucide-react';
import {dictionaryCategories,type Entry,type Explanation} from '@/lib/dictionary';
import './dictionary.css';
type Results={entries:Entry[];total:number;hasMore:boolean;meta:{available:number;mongolian:number;english:number;categories:Record<string,number>}};
type Answer={explanation:Explanation;sources:{word:string;url:string}[];model:string};
export default function Dictionary(){
 const [input,setInput]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('Бүгд'),[offset,setOffset]=useState(0);
 const [results,setResults]=useState<Results|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Entry|null>(null);
 const [context,setContext]=useState(''),[showContext,setShowContext]=useState(false),[answer,setAnswer]=useState<Answer|null>(null),[aiBusy,setAiBusy]=useState(false),[aiError,setAiError]=useState('');
 const [settings,setSettings]=useState(false),[key,setKey]=useState(''),[password,setPassword]=useState(''),[model,setModel]=useState('gpt-4.1-mini');
 const aiController=useRef<AbortController|null>(null),initialized=useRef(false),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const q=new URLSearchParams(location.search).get('q')?.slice(0,300)||'';setQuery(q);setInput(q);initialized.current=true;return()=>aiController.current?.abort();},[]);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setSelected(null);
 fetch(`/api/search?${new URLSearchParams({q:query,category,offset:String(offset)})}`,{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setResults(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message||'Хайлт амжилтгүй боллоо.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
 return()=>controller.abort();},[query,category,offset]);
 useEffect(()=>{if(settings)dialog.current?.showModal();else dialog.current?.close();},[settings]);
 function search(value:string){const q=value.trim();aiController.current?.abort();setAiBusy(false);setAnswer(null);setAiError('');setInput(q);setQuery(q);setOffset(0);setSelected(null);if(initialized.current)history.replaceState(null,'',q?`?q=${encodeURIComponent(q)}`:location.pathname);}
 function submit(e:FormEvent){e.preventDefault();search(input);}
 async function explain(word:string){if(!word.trim())return;if(!key&&!password){setSettings(true);setAiError('AI тайлбар авахын тулд холболтоо тохируулаад дахин товшино уу.');return;}
 aiController.current?.abort();const controller=new AbortController();aiController.current=controller;setAiBusy(true);setAnswer(null);setAiError('');try{const response=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json',...(key?{'x-openai-key':key}:{'x-research-password':password})},body:JSON.stringify({query:word,context,model}),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setAnswer(data);}catch(e){if((e as Error).name!=='AbortError')setAiError((e as Error).message);}finally{if(!controller.signal.aborted)setAiBusy(false);}}
 const target=selected?.word||query;
 return <div className="dictionary-app"><header className="dict-header"><Link href="/" className="dict-brand"><span className="dict-mark">у</span>утга<span className="dict-brand-sub">МОНГОЛ ХЭЛНИЙ ТОЛЬ</span></Link><nav aria-label="Үндсэн цэс"><Link href="/" aria-current="page">Тайлбар толь</Link><Link href="/research">Судалгааны лаборатори <ArrowRight size={15}/></Link></nav><button className="dict-icon" aria-label="AI холболт тохируулах" onClick={()=>setSettings(true)}><Settings2 size={19}/><span>AI холболт</span></button></header>
 <main className="dict-main"><section className="dict-hero"><div className="dict-eyebrow"><span/> ҮГ БҮРИЙН ЦААНА НЭГ УТГА</div><h1>Үгийг мэд.<br/><em>Утгыг нь ойлго.</em></h1><p>Үг, хэлц, зүйр үг, ёгтлол, монгол ахуй.<br className="mobile-break"/> Утга, хэрэглээ, жишээг нэг дороос.</p><form className="dict-search" onSubmit={submit}><Search size={23}/><input aria-label="Үг, хэллэг хайх" value={input} onChange={e=>setInput(e.target.value)} maxLength={300} placeholder="Ямар үгийн утгыг мэдмээр байна?"/><button type="submit">Хайх <ArrowRight size={19}/></button></form><div className="dict-try"><span>Жишээ нь</span>{['гар','нүд','ажил','гэр'].map(w=><button key={w} onClick={()=>{setCategory('Бүгд');search(w);}}>{w} <ArrowRight size={12}/></button>)}</div><button className="dict-context-toggle" onClick={()=>setShowContext(!showContext)} aria-expanded={showContext}><ChevronDown size={15}/> Өгүүлбэр, нөхцөл нэмэх <span>AI тайлбарт</span></button>{showContext&&<label className="dict-context">Ямар өгүүлбэрт хэрэглэснийг бичээрэй<textarea value={context} maxLength={2000} onChange={e=>setContext(e.target.value)} placeholder="Жишээ: Хоцорч ирэхэд нь ‘Яасан эрт ирдэг юм бэ’ гэж хэлэв."/></label>}</section>
 <div className="dict-stats"><div><BookOpen size={19}/><strong>{results?results.meta.available.toLocaleString():'…'}</strong><span>үг, хэллэг</span></div><div><span className="dict-dot"/>Эх сурвалжтай тайлбар</div><div><Sparkles size={17}/> AI-аар дэлгэрүүлэх боломжтой</div></div>
 <section className="dict-content" aria-label="Тайлбар толь"><div className="dict-section-top"><div><div className="dict-eyebrow">МОНГОЛ ХЭЛ · ӨВ СОЁЛ</div><h2>{query?`“${query}”`:'Утгын ертөнцөөр'}</h2></div><span className="dict-result-count" role="status">{busy?'Хайж байна…':error?'':`${results?.total.toLocaleString()||0} илэрц`}</span></div><div className="dict-filters" aria-label="Ангилал">{['Бүгд',...dictionaryCategories].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>{setCategory(c);setOffset(0);setAnswer(null);setAiError('');aiController.current?.abort();setAiBusy(false);}}>{c}{c!=='Бүгд'&&results&&<small>{(results.meta.categories[c]||0).toLocaleString()}</small>}</button>)}</div>
 {error&&<div className="dict-notice" role="alert">{error}<button onClick={()=>location.reload()}>Дахин ачаалах</button></div>}
 {busy?<div className="dict-loading"><LoaderCircle className="dict-spin"/> Тайлбаруудыг хайж байна…</div>:!error&&<>{selected?<article className="dict-detail"><button className="dict-back" onClick={()=>{setSelected(null);setAnswer(null);setAiError('');aiController.current?.abort();setAiBusy(false);}}><ArrowLeft size={16}/> Илэрц рүү буцах</button><div className="dict-entry-top"><span className="dict-tag">{selected.category}</span><span>{selected.language==='en'?'Англи эхийн тайлбар':selected.status==='editorial'?'Редакцын жишээ · хянаагүй':'Монгол эхийн тайлбар'}</span></div><h2>{selected.word}</h2><ol className="dict-meanings">{selected.meanings.map((m,i)=><li key={i}>{m}</li>)}</ol>{selected.examples.length>0&&<section className="dict-examples"><h3>Хэрэглээ ба жишээ</h3>{selected.examples.map((e,i)=><div key={i}><strong>{e.sentence}</strong><p>{e.explanation}</p></div>)}</section>}{selected.related.length>0&&<div className="dict-related"><h3>Холбоотой үг, хэллэг</h3>{selected.related.map((r,i)=><button key={i} onClick={()=>{setCategory('Бүгд');search(r);}}>{r} <ArrowRight size={13}/></button>)}</div>}<div className="dict-source"><span>Эх сурвалж</span>{selected.sourceUrl?<a href={selected.sourceUrl} target="_blank" rel="noreferrer">{selected.source} <ExternalLink size={13}/></a>:<span>{selected.source}</span>}<small>{selected.status==='source'?'Нээлттэй, олон нийтийн толь. Алдаа болон дутуу тайлбар байж болно.':'Судалгааны эхлэх жишээ. Шинжээчийн баталгаажуулалт хийгдээгүй.'}</small></div></article>:results?.entries.length?<div className="dict-grid">{results.entries.map(entry=><button key={entry.id} className="dict-card" onClick={()=>{setSelected(entry);setAnswer(null);setAiError('');aiController.current?.abort();setAiBusy(false);}}><div className="dict-entry-top"><span className="dict-tag">{entry.category}</span><ArrowRight size={18}/></div><h3>{entry.word}</h3><p>{entry.meanings[0]}</p><div className="dict-card-bottom"><span>{entry.language==='en'?'Англи эх':entry.status==='editorial'?'Редакцын жишээ':'Викитоль · монгол'}</span><span>{entry.meanings.length>1?`${entry.meanings.length} утга`:'Тайлбар үзэх'}</span></div></button>)}</div>:<div className="dict-empty"><BookOpen size={32}/><h3>Энэ хайлтаар тайлбар олдсонгүй</h3><p>Үгийн үндсэн хэлбэрээр эсвэл өөр ангиллаар хайгаарай.<br/>AI холбосон бол доороос утгыг нь тайлбарлуулж болно.</p>{category!=='Бүгд'&&<button onClick={()=>setCategory('Бүгд')}>Бүх ангиллаас хайх</button>}</div>}
 {!selected&&results&&results.total>24&&<div className="dict-pages"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-24))}><ArrowLeft size={16}/> Өмнөх</button><span>{offset+1}–{Math.min(offset+24,results.total)} / {results.total.toLocaleString()}</span><button disabled={!results.hasMore} onClick={()=>setOffset(offset+24)}>Дараах <ArrowRight size={16}/></button></div>}</>}
 {target&&<section className="dict-ai"><div className="dict-ai-heading"><span className="dict-ai-icon"><Sparkles size={24}/></span><div><h3>“{target}” — утгыг нь дэлгэрүүлье</h3><p>Шууд ба далд утга, хэрэглэх нөхцөл, тайлбартай хоёр жишээ.</p></div><button disabled={aiBusy} onClick={()=>explain(target)}>{aiBusy?<LoaderCircle className="dict-spin" size={17}/>:<Sparkles size={17}/>} {aiBusy?'Тайлбарлаж байна…':'AI-аар тайлбарлуулах'}</button></div><small>AI-ийн тайлбар алдаатай байж болно. Жишээ өгүүлбэрүүдийг AI зохионо. API холболт шаардлагатай.</small>{aiError&&<p className="dict-ai-error" role="alert">{aiError}</p>}{answer&&<div className="dict-ai-answer" aria-live="polite"><span className="dict-tag">AI тайлбар · {answer.model}</span><h3>{answer.explanation.word}</h3><p>{answer.explanation.meaning}</p>{answer.explanation.literalMeaning&&<p><strong>Шууд утга:</strong> {answer.explanation.literalMeaning}</p>}{answer.explanation.usage&&<p><strong>Хэрэглэх нөхцөл:</strong> {answer.explanation.usage}</p>}{answer.explanation.examples.length>0&&<><h4>AI-ийн зохиосон жишээнүүд</h4>{answer.explanation.examples.map((e,i)=><div className="dict-ai-example" key={i}><strong>{i+1}. {e.sentence}</strong><p>{e.explanation}</p></div>)}</>}{answer.explanation.caution&&<p className="dict-caution">{answer.explanation.caution}</p>}{answer.explanation.related.map((r,i)=><button className="dict-related-link" key={i} onClick={()=>search(r)}>{r} ↗</button>)}{answer.sources.length>0&&<div className="dict-ai-sources">AI-д өгсөн лавлах эхүүд: {answer.sources.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer">{s.word} ↗</a>)}</div>}</div>}</section>}
 </section><section className="dict-bottom-note"><div className="dict-mark">у</div><div><h3>Хэлээ мэдэх нь өөрийгөө танихын эхлэл.</h3><p>Нээлттэй эх сурвалж, монгол тайлбар, хэрэглээний жишээг холбосон толь.<br/>Англи эхтэй үгсийг тусад нь тэмдэглэнэ. Тайлбарыг эх сурвалжтай нь нягтлаарай.</p></div></section></main>
 <footer className="dict-footer"><span>© {new Date().getFullYear()} Утга · Монгол хэл ба хиймэл оюун</span><div><a href="https://mn.wiktionary.org/" target="_blank" rel="noreferrer">Викитоль</a><a href="https://kaikki.org/dictionary/Mongolian/" target="_blank" rel="noreferrer">Kaikki</a><a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">Өгөгдөл: CC BY-SA 4.0</a></div></footer>
 <dialog ref={dialog} className="dict-dialog" onCancel={()=>setSettings(false)} onClick={e=>{if(e.target===e.currentTarget)setSettings(false);}}><div className="dict-dialog-top"><h2>AI холболт</h2><button className="dict-icon" onClick={()=>setSettings(false)} aria-label="Хаах"><X size={20}/></button></div><p>Толь доторх хайлт түлхүүргүй ажиллана. AI тайлбар авахдаа өөрийн OpenAI API түлхүүр эсвэл сайтын эзний өгсөн нэвтрэх кодыг ашиглана.</p><label>OpenAI API түлхүүр<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value.trim())} placeholder="sk-…"/></label><label>Эсвэл сайтын нэвтрэх код<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} /></label><label>Загвар<input value={model} maxLength={100} onChange={e=>setModel(e.target.value)} /></label><p className="dict-security-note">Түлхүүрийг энэ хуудасны санах ойд түр хадгална. Дахин ачаалахад арилна. Хүсэлт сайтын серверээр дамжин OpenAI руу очно; API хэрэглээ төлбөртэй байж болно.</p><button className="dict-primary" onClick={()=>setSettings(false)}>Тохиргоог ашиглах</button></dialog></div>;
}
